steps:
  - name: gcr.io/cloud-builders/docker
    args: [
      "build", "-t", "gcr.io/$PROJECT_ID/fe-admin:$COMMIT_SHA", "."
    ]

  - name: gcr.io/cloud-builders/docker
    args: [
      "push", "gcr.io/$PROJECT_ID/fe-admin:$COMMIT_SHA"
    ]

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - fe-admin
      - --image=gcr.io/$PROJECT_ID/fe-admin:$COMMIT_SHA
      - --region=asia-southeast1
      - --platform=managed
      - --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - gcr.io/$PROJECT_ID/fe-admin:$COMMIT_SHA